### ISSUE TITLE
Fails to get memory reservation required from task definitions

### ISSUE THREAD

**Issue by drewbo** [JeffDownie/aws-ecs-autoscaler#3]
I think [this line](https://github.com/JeffDownie/aws-ecs-autoscaler/blob/master/lib/dataUtils.js#L13) should pick `memoryReservation` rather than `memory` (was seeing `NaN` in an implementation of this)

**Comment by JeffDownie** [comment]
`memoryReservation` is a [soft limit](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-memoryreservation), whereas setting a `memory` parameter on a container definition is a [hard limit](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-memory). Instead of switching the properties, I think it should just choose `memory || memoryReservation` (in that order).

**Comment by JeffDownie** [comment]
I'm surprised I hadn't noticed that `NaN` yet! It should work now though in 0.1.5 with `memory`, `memoryReservation` and `cpu` correctly, as far as I can tell.

Thanks!
